name: Selenium CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
      
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run Selenium Tests
      env:
        DISPLAY: :99  # Required for headless testing
      run: |
        cd ./client/tests
        python dir.py
        python run_testing_pipeline.py
        # python run_testing_pipeline.py > ./test-results/main_test.log 2>&1

    - name: Archive Selenium Test Results
      if: always()  # Always upload artifacts even if the test fails
      uses: actions/upload-artifact@v3
      with:
        name: selenium-test-results
        path: ./client/tests/test-results/  # Upload the `test-results` directory as an artifact
